/**
 * snoPalette.ts - the 256 colours an object's indices name.
 *
 * DECK-0003 §1.3 made a colour one number instead of three, which is what took
 * a worst-case vertex from 52 bytes to 32 and made a colour on every face
 * affordable. The number is an index into a palette, and this module is where
 * an object's palette is decided and where the two directions of the lookup
 * live.
 *
 * Named snoPalette rather than palette because lib/palette.ts is already the
 * scene's visual language, the colours the world and the terrain field are
 * drawn in. Those are how this app looks; these are what a shard can be.
 *
 * The model keeps colours as RGB floats, not indices, and that is deliberate.
 * Every renderer, clipper and buffer in this app already speaks RGB, and
 * making them all speak indices would be a large change to buy nothing: the
 * index only matters on the wire. What matters instead is that the workshop
 * can only produce colours that are in the palette, so the trip out and back
 * is exact rather than approximate. `nearest` exists for the one case where it
 * is not: a model built before this existed.
 */

import raw from './snoPalette.json'

export type Rgb = [number, number, number]
/** A palette as the wire carries it: 2 to 256 entries of three integers 0..255. */
export type Palette = Rgb[]

/** DECK-0003 §1.3a. The one registered name, and the default. */
export const BUILT_IN_NAME = 'cyberspace-neon-256'

const hexToBytes = (h: string): Rgb => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16)) as Rgb

/** The built-in, as bytes. Generated by the deck's sno-palette.mjs; never edit by hand. */
export const BUILT_IN: Palette = (raw as { colors: string[] }).colors.map(hexToBytes)

/** The built-in as the model holds colour: floats 0..1. */
export const BUILT_IN_RGB: Rgb[] = BUILT_IN.map((c) => c.map((n) => n / 255) as Rgb)

/** A palette entry as the model holds colour. */
export function toModel(c: Rgb): Rgb {
  return c.map((n) => n / 255) as Rgb
}

/** A model colour as a palette entry. */
export function toBytes(c: Rgb): Rgb {
  return c.map((n) => Math.max(0, Math.min(255, Math.round(n * 255)))) as Rgb
}

/**
 * A palette field as read from a payload, or null when it is not one.
 *
 * `fetched` is the content of a referenced palette event when the caller has
 * managed to get it (§1.3b). A reference that has not resolved is the built-in
 * rather than a failure, because a reference is never load-bearing: the worst
 * case is an object drawn in the wrong colours and never one that cannot be
 * drawn.
 */
export function resolvePalette(field: unknown, fetched?: string | null): Palette | null {
  if (field === undefined || field === null) return BUILT_IN
  if (typeof field === 'string') {
    if (field === BUILT_IN_NAME) return BUILT_IN
    if (isPaletteRef(field)) return (fetched ? parsePaletteContent(fetched) : null) ?? BUILT_IN
    return null
  }
  return readPalette(field)
}

/** Whether a palette field names an event rather than a built-in. */
export function isPaletteRef(field: unknown): field is string {
  return typeof field === 'string' && /^naddr1[023456789acdefghjklmnpqrstuvwxyz]{20,}$/.test(field)
}

/** A palette carried in a payload, or null when it is not a valid one. */
export function readPalette(field: unknown): Palette | null {
  if (!Array.isArray(field) || field.length < 2 || field.length > 256) return null
  const out: Palette = []
  for (const e of field) {
    if (!Array.isArray(e) || e.length !== 3) return null
    if (!e.every((n) => Number.isInteger(n) && n >= 0 && n <= 255)) return null
    out.push([e[0], e[1], e[2]] as Rgb)
  }
  return out
}

/**
 * A palette event's content, or null when it is not one (§1.3b).
 *
 * Generous about shape and silent about kind, because palettes on nostr are
 * somebody else's problem and partly solved already. A reader that accepts the
 * obvious form will read whatever convention wins without this app being
 * revised.
 */
export function parsePaletteContent(text: string): Palette | null {
  let raw: unknown
  try { raw = JSON.parse(text) } catch { return null }
  if (!Array.isArray(raw) || raw.length < 2 || raw.length > 256) return null
  const out: Palette = []
  for (const e of raw) {
    if (typeof e === 'string' && /^#[0-9a-fA-F]{6}$/.test(e)) out.push(hexToBytes(e))
    else if (Array.isArray(e) && e.length === 3 && e.every((n) => Number.isInteger(n) && n >= 0 && n <= 255)) out.push([e[0], e[1], e[2]] as Rgb)
    else return null
  }
  return out
}

/* --------------------------------------------------------------------------
 * The lookup, both ways
 * ------------------------------------------------------------------------ */

/** sRGB to OKLab, so "nearest" means nearest to look at rather than nearest to subtract. */
function oklab(c: Rgb): [number, number, number] {
  const lin = (v: number): number => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4)
  const r = lin(c[0] / 255), g = lin(c[1] / 255), b = lin(c[2] / 255)
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  return [
    0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s,
  ]
}

/**
 * The index of a colour in a palette: the exact entry when there is one, and
 * otherwise the nearest.
 *
 * Exact is the normal case, because the workshop only offers palette colours.
 * The nearest path is for a model built before the palette existed, where
 * snapping is the alternative to throwing the colour away.
 */
export function indexOf(palette: Palette, c: Rgb): number {
  for (let i = 0; i < palette.length; i++) {
    const p = palette[i]
    if (p[0] === c[0] && p[1] === c[1] && p[2] === c[2]) return i
  }
  const want = oklab(c)
  let best = 0, bestD = Infinity
  for (let i = 0; i < palette.length; i++) {
    const got = oklab(palette[i])
    const d = (got[0] - want[0]) ** 2 + (got[1] - want[1]) ** 2 + (got[2] - want[2]) ** 2
    if (d < bestD) { bestD = d; best = i }
  }
  return best
}

/** The model colour an index names, clamped into the palette. */
export function colorAt(palette: Palette, index: number): Rgb {
  const i = Number.isInteger(index) && index >= 0 && index < palette.length ? index : 0
  return toModel(palette[i])
}

/* --------------------------------------------------------------------------
 * The workshop's side of it
 * ------------------------------------------------------------------------ */

const hex2 = (n: number): string => n.toString(16).padStart(2, '0')

/** A palette entry as the hex the colour controls pass around. */
export function hexAt(palette: Palette, index: number): string {
  const c = palette[Number.isInteger(index) && index >= 0 && index < palette.length ? index : 0]
  return `#${hex2(c[0])}${hex2(c[1])}${hex2(c[2])}`
}

/**
 * The nearest palette colour to a hex, as a hex.
 *
 * Every colour the workshop offers goes through here, so what is on the bench
 * is always a colour the object can actually carry and the trip to the wire
 * and back is exact. Without it the mixer would let somebody choose a colour
 * that shifts the moment they publish: across the sRGB cube the mean snap is
 * about 0.041 in OKLab and the worst about 0.13, where a just-noticeable
 * difference is roughly 0.02. That is a visible change to your own object,
 * arriving at the least welcome moment.
 */
export function snapHex(palette: Palette, hex: string): string | null {
  const m = /^#?([0-9a-fA-F]{6})$/.exec(hex.trim())
  // Null rather than the first entry: something that is not a colour is a
  // caller's mistake, and quietly turning it into a real colour would hide it.
  if (!m) return null
  const want = [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) as Rgb
  return hexAt(palette, indexOf(palette, want))
}

/** The whole built-in as hex, for a swatch grid. */
export const BUILT_IN_HEX: string[] = BUILT_IN.map((_, i) => hexAt(BUILT_IN, i))
