#!/usr/bin/env node
/**
 * Regenerates src/lib/hyperspace/grandfathered.ts from the spec repository's
 * decks/grandfathered-v1-hyperjumps.txt (DECK-0001 section 5.8).
 *
 *   node scripts/grandfathered.mjs [path to a cyberspace clone] [ref]
 *
 * Defaults: ../cyberspace and origin/master. The list is read from the ref
 * with git show, never from the clone's working tree, and the header of the
 * generated file names the commit the ref resolved to. Fetch the clone first.
 *
 * The sidestep list (grandfathered-v2-sidesteps.txt, CYBERSPACE_V2.md 6.16)
 * is not generated here: cyberspace-core embeds it as
 * GRANDFATHERED_V2_SIDESTEPS, and a core bump carries it.
 */

import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const LIST = 'decks/grandfathered-v1-hyperjumps.txt'
const OUT = new URL('../src/lib/hyperspace/grandfathered.ts', import.meta.url)
const [repo = '../cyberspace', ref = 'origin/master'] = process.argv.slice(2)

const git = (...args) => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8' })
const commit = git('rev-parse', `${ref}^{commit}`).trim()
const text = git('show', `${commit}:${LIST}`)

// Section 5.8, in the format of CYBERSPACE_V2.md 6.16: lines starting with #
// are comments; every other non-empty line starts with a 64-character
// lowercase hex event id, and the rest is commentary.
const entries = []
for (const line of text.split('\n')) {
  const trimmed = line.trim()
  if (trimmed === '' || trimmed.startsWith('#')) continue
  const [id, ...rest] = trimmed.split(/\s+/)
  if (!/^[0-9a-f]{64}$/.test(id)) throw new Error(`not a 64-hex event id: ${trimmed}`)
  entries.push({ id, note: rest.join(' ') })
}
if (new Set(entries.map((e) => e.id)).size !== entries.length) throw new Error(`${LIST} lists an id twice`)

const out = `/**
 * GENERATED by scripts/grandfathered.mjs. Do not edit by hand; rerun it.
 *
 * Source: arkin0x/cyberspace ${commit}, ${LIST}
 *
 * The rides published before ride openings version 2 and exempt under
 * DECK-0001 section 5.8, by event id: an event listed here carries no \`mn\`
 * tag, and a verifier accepts its root and openings without re-checking them
 * and checks everything else. Commentary per line, from the source: pubkey,
 * created_at, from_height->B, audit.
 */
export const GRANDFATHERED_V1_HYPERJUMPS_SOURCE = '${commit}'

export const GRANDFATHERED_V1_HYPERJUMPS: ReadonlySet<string> = new Set([
${entries.map((e) => `  '${e.id}', // ${e.note}`).join('\n')}
])
`
writeFileSync(OUT, out)
console.log(`${entries.length} ids from ${commit} -> src/lib/hyperspace/grandfathered.ts`)
