/**
 * chainVectors.test.ts - the cross-implementation golden vectors for chain
 * rules revision 2026-09-28-virtual-brackets, as spec commit 912f3d7 states
 * it, run through ONOSENDAI's chain review.
 *
 * The file is copied unchanged from arkin0x/cyberspace-cli (vectors/, commit
 * 85f4e44, generated by scripts/gen_chain_vectors.py; format in that
 * directory's README). Every vector is run the way ONOSENDAI reads a chain:
 * inauthentic events are discarded first, as the relay pool and the store do
 * where events come in (spec §8.7.3), and buildChain resolves the rest and
 * marks the first break. A vector agrees when the active chain, the first
 * invalid event and the position (the frozen one, on an invalid chain) are
 * the ones the vector expects; for a valid chain also the head, the open
 * bracket and the skipped actions.
 *
 * ONOSENDAI is a viewer, not a verifier (events.ts, parseAction): it checks
 * no proof and keeps no block line, so a vector whose break is a proof or
 * a ride's place on the line reads as valid here. Those are listed in
 * NOT_CHECKED with the reason code they turn on, and the test holds that
 * ONOSENDAI resolves the same chain and sees no other break before the
 * expected one. Any other disagreement fails.
 */

import { describe, it, expect } from 'vitest'
import { verifyEvent, type VerifiedEvent } from 'nostr-tools/pure'
import vectors from './vectors/chain-rules-2026-09-28-virtual-brackets.json'
import { CHAIN_RULES_REVISION, buildChain, chainHead, firstBreak, openBracket, type NostrEvent } from '../events'

interface Expected {
  valid: boolean
  chain: string[]
  position: string | null
  head?: string
  open_bracket?: string | null
  skipped?: string[]
  reason?: string
  invalid_at?: string | null
  invalid_index?: number | null
}

interface Vector { name: string; events: NostrEvent[]; expected: Expected }

/**
 * Reason codes ONOSENDAI does not check, because it is a viewer and a
 * verifier does this work. Most turn on a proof or on the block line: the
 * proofs themselves, the station, an as_of beyond the tip, the stop of B.
 * Three DECK-0001 ride rules need neither and are still not checked here: a
 * first ride with no as_of, an as_of below B (both `hyperjump-as-of`, §4.2,
 * §4.3), and a later ride whose from_height is not the previous ride's B
 * (`hyperjump-from-height`, §4.3). They predate spec PR #46 and are left
 * for a follow-up, after a look at which published rides they would break.
 */
const NOT_CHECKED: ReadonlySet<string> = new Set([
  'hop-proof', 'sidestep-proof', 'enter-hyperspace-proof', 'hyperjump-proof',
  'hyperjump-station', 'hyperjump-as-of', 'hyperjump-from-height', 'hyperjump-stop',
])

const identity = vectors.verify_with.identity

/** What ONOSENDAI makes of one vector, in the vector's own terms. */
function review(v: Vector): Expected {
  // §8.7.3: only authentic events by the identity take part.
  const events = v.events.filter((e) => e.pubkey === identity && verifyEvent(structuredClone(e) as VerifiedEvent))
  const chain = buildChain(events, identity)
  if (chain.length === 0) return { valid: false, chain: [], position: null, reason: 'no-spawn', invalid_at: null, invalid_index: null }
  const ids = chain.map((a) => a.id)
  const position = chainHead(chain)!.coordHex
  const broken = firstBreak(chain)
  if (broken) return { valid: false, chain: ids, position, invalid_at: broken.action.id, invalid_index: broken.index }
  return {
    valid: true,
    chain: ids,
    position,
    head: ids[ids.length - 1],
    open_bracket: openBracket(chain)?.id ?? null,
    skipped: chain.filter((a) => a.role === 'skipped').map((a) => a.id),
  }
}

describe(`golden chain vectors, revision ${CHAIN_RULES_REVISION} (spec 912f3d7, cyberspace-cli 85f4e44)`, () => {
  it('lock the revision this client implements', () => {
    expect(vectors.chain_rules_revision).toBe(CHAIN_RULES_REVISION)
    expect(vectors.spec.commit).toBe('912f3d70e4d15d70054e9fa98646098a1c216d47')
  })

  for (const v of vectors.vectors as unknown as Vector[]) {
    const want = v.expected
    if (!want.valid && want.reason && NOT_CHECKED.has(want.reason)) {
      it(`${v.name}: the same chain, and no break before the ${want.reason} that only a verifier sees`, () => {
        const got = review(v)
        expect(got.chain).toEqual(want.chain)
        if (!got.valid) expect(got.invalid_index!).toBeGreaterThan(want.invalid_index!)
      })
      continue
    }
    it(`${v.name}: ${want.valid ? 'valid' : `invalid at ${want.invalid_index} (${want.reason})`}`, () => {
      const got = review(v)
      const { reason: _reason, ...rest } = want
      if (want.valid) expect(got).toEqual(rest)
      else expect({ ...got, reason: undefined }).toEqual({ ...rest, reason: undefined })
    })
  }
})
